version: 2

aliases:
  - &container_config
    docker:
      - image: circleci/node:10.15.1-browsers

jobs:
  test:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install deps
          command: yarn
      - run:
          name: Run TestCafe tests
          command: yarn test

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
